In [2]:
import numpy as np

## Array

In [3]:
# Create an array containing the sales quantity of a product for each month (from January to May)
arr1 = np.array([120, 85, 230, 150, 60])
print(arr1)
arr1


[120  85 230 150  60]


array([120,  85, 230, 150,  60])

In [10]:
arr1.dtype

dtype('int64')

In [11]:
type(arr1)

numpy.ndarray

In [ ]:
# Array object has 2 components: properties, methods (functions)
# Access:
# arrayname.properties
# arrayname.method()

## Properties

In [13]:
type(arr1)

numpy.ndarray

In [4]:
# data type of elements in array
arr1.dtype

dtype('int64')

In [14]:
# count the number of elements in the array
arr1.size

5

In [5]:
# 1-dimensional array, with 5 elements
arr1.shape

(5,)

In [25]:
# 1-dimensional array
arr1.ndim

1

In [26]:
# size
arr1.itemsize 

8

In [29]:
# array-size
arr1.nbytes

40

In [31]:
# maximum
print(arr1.max())

230


#### Create array from tuple, using dtype with different parameter values

In [6]:
# Create an array containing the ages of 5 students from a tuple
arr_age = np.array((21, 25, 29, 30, 32), dtype='i1')
arr_age


array([21, 25, 29, 30, 32], dtype=int8)

In [39]:
arr_age.dtype

dtype('int8')

In [7]:
# Create an array to store the heights of 5 students
arr_height = np.array([160.5, 165.7, 170.2, 175.3, 180.0])
arr_height.nbytes


40

In [8]:
arr_height.dtype

dtype('float64')

In [9]:
# Create an array to store the heights of 5 students
# with the following data types:
# - signed integer 2 bytes (dtype='i2')
# - unsigned integer 1 byte (dtype='u1')
# - floating point 2 bytes (dtype='float16')
arr_height = np.array([160.5, 165.7, 170.2, 175.3, 180.0], dtype='f4')
arr_height


array([160.5, 165.7, 170.2, 175.3, 180. ], dtype=float32)

In [43]:
arr_height.dtype

dtype('float32')

## Create arrays from utility functions


In [10]:
# Create an array with 10 elements, all initialized to 0
arr0 = np.zeros((10,), dtype=int)
arr0


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
# Create an array with 10 elements of value 1
arr_1 = np.ones((10,), dtype=int)
print(arr_1)


[1 1 1 1 1 1 1 1 1 1]


In [12]:
# Create an array with 10 elements, all initialized to 4
arr2 = np.full((10,), fill_value=4)
print(arr2)


[4 4 4 4 4 4 4 4 4 4]


In [13]:
# Create an array with 10 elements from 0 to 9
arr3 = np.arange(10)  # arange(0, 10, 1)
print(arr3)


[0 1 2 3 4 5 6 7 8 9]


In [14]:
# Create an array with 9 elements from 1 to 9
arr4 = np.arange(1, 10)
print(arr4)


[1 2 3 4 5 6 7 8 9]


In [15]:
# Create an array with even numbers less than 10
arr5 = np.arange(0, 10, 2)
print(arr5)


[0 2 4 6 8]


In [16]:
# Create an array with elements from 10 to 1
arr5 = np.arange(10, 0, -1)
print(arr5)


[10  9  8  7  6  5  4  3  2  1]


In [ ]:
# linspace(start,stop,num,endpoint)
# endpoint = True => bins= (stop - start)/(num - 1)
# endpoint = False => bins= (stop - start)/(num)

In [17]:
# Create an array with 15 evenly spaced integers from 2 to 30 (including 30)
arr6 = np.linspace(2, 30, 15, endpoint=True, retstep=True)
print(arr6)


(array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24., 26.,
       28., 30.]), 2.0)


In [18]:
# Create an array with 15 evenly spaced values from 1 to 10 (excluding 10)
arr6 = np.linspace(1, 10, 15, endpoint=False, retstep=True)
print(arr6)


(array([1. , 1.6, 2.2, 2.8, 3.4, 4. , 4.6, 5.2, 5.8, 6.4, 7. , 7.6, 8.2,
       8.8, 9.4]), 0.6)


In [19]:
# Create an array with 5 evenly spaced values from 2 to 10 (including 10)
arr7 = np.linspace(2, 10, 5, endpoint=True)
print(arr7)


[ 2.  4.  6.  8. 10.]


In [20]:
# Create an array with 5 evenly spaced values from 2 to 10 (excluding 10)
arr8 = np.linspace(2, 10, 5, endpoint=False)
print(arr8)


[2.  3.6 5.2 6.8 8.4]


In [21]:
# Create an array with 4 random values between 0 and 1 (excluding 1)
arr9 = np.random.rand(4)
print(arr9)


[0.39021806 0.60798251 0.16494066 0.64339205]


In [22]:
# Create an array with 10 random integers between 0 and 5
arr10 = np.random.randint(6, size=10)
print(arr10)


[0 4 0 1 4 3 3 3 3 0]


In [84]:
np.random.seed(8)
arr10 = np.random.randint(low=1,high=6, size=10)
print(arr10)

[4 5 2 2 3 1 4 1 1 5]


In [23]:
# Create an array with 5 random integers between 0 and 2
np.random.seed(8)
arr11 = np.random.randint(0, 3, 5)
print(arr11)


[0 1 1 1 2]


In [24]:
# Create an array from the file heights.txt
heights = np.genfromtxt('heights.txt', delimiter=',')  # Heights of baseball players (in inches)
print(heights[:10])
print(heights.size)


[74. 74. 72. 72. 73. 69. 69. 71. 76. 71.]
1015


## Retrieve
### Retrieve 1 element

In [87]:
arr1

array([120,  85, 230, 150,  60])

In [88]:
arr1[0]  # 1st element

np.int64(120)

In [89]:
arr1[-1] # last element

np.int64(60)

In [90]:
arr1[3] # index 3

np.int64(150)

In [91]:
heights[1014]

np.float64(73.0)

In [92]:
heights[-1]

np.float64(73.0)

### Retrieve several elements

In [100]:
arr1

array([120,  85, 230, 150,  60])

In [25]:
# Values of the elements at indices 0, 1, and 4
lst_index = [0, 1, 4]
arr1[lst_index]


array([120,  85,  60])

### Slice

In [27]:
#Display the value of the first 3 elements index 0,1,2
arr1[:3]  

array([120,  85, 230])

In [26]:
#Display the value of the last 2 elements -2,-1
arr1[-2:]

array([150,  60])

In [28]:
#Display odd index element values
arr1[1::2]

array([ 85, 150])

In [99]:
# Display the reversed array of arr1
arr1[::-1]

array([ 60, 150, 230,  85, 120])

### Retrieve element by condition

In [102]:
arr1

array([120,  85, 230, 150,  60])

In [104]:
arr1 > 100

array([ True, False,  True,  True, False])

In [103]:
# Display elements with values ​​>100
arr1[arr1 > 100]

array([120, 230, 150])

### Retrieve elements based on multiple conditions

In [118]:
# Display elements with values ​​from 100 to 200
arr1[(arr1 >= 100) & (arr1 <= 200)] # and

array([120, 150])

In [110]:
# Display elements with values ​​less than 100 or greater than 200
arr1[(arr1 < 100) | (arr1 > 200)] # or

array([ 85, 230,  60])

In [111]:
# Display elements with values no greater than 100
arr1[~(arr1 > 100)]# not

array([85, 60])

### Retrieve elements based on conditions with np.where

In [115]:
arr1[arr1 > 100]

array([120, 230, 150])

In [113]:
arr1

array([120,  85, 230, 150,  60])

In [112]:
# Index of elements with value > 100?
idx = np.where(arr1 > 100)
idx

(array([0, 2, 3]),)

In [114]:
# Show elements with value > 100
arr1[idx]

array([120, 230, 150])

## Add, delete, edit array data
### Add element to the end of array

In [119]:
arr1

array([120,  85, 230, 150,  60])

In [120]:
np.concatenate ([arr1,[200]])

array([120,  85, 230, 150,  60, 200])

In [121]:
arr1

array([120,  85, 230, 150,  60])

In [122]:
# Add value to the end of array arr1
arr1 = np.concatenate ([arr1, [200]])
arr1

array([120,  85, 230, 150,  60, 200])

In [123]:
# add multiple values to the end of array arr1
arr1= np.concatenate([arr1, [170, 95, 210]])
arr1

array([120,  85, 230, 150,  60, 200, 170,  95, 210])

### Insert an element into an array at a specified position, using np.insert()

In [124]:
arr1 = np.array([120, 85, 230, 150, 60])
arr1

array([120,  85, 230, 150,  60])

In [125]:
# Insert an element into the array
arr4 = np.insert(arr1, 4, 100)
arr4

array([120,  85, 230, 150, 100,  60])

In [126]:
# Insert multiple elements into the array
arr4 = np.insert(arr1, 5, [80, 70])
arr4

array([120,  85, 230, 150,  60,  80,  70])

In [127]:
arr1

array([120,  85, 230, 150,  60])

In [128]:
# Insert multiple elements into the array at multiple positions
arr4 = np.insert(arr1, [1,4], [80, 70])
arr4

array([120,  80,  85, 230, 150,  70,  60])

### Delete


In [129]:
arr1 = np.array([120, 85, 230, 150, 60])
arr1

array([120,  85, 230, 150,  60])

In [130]:
# 1st
np.delete(arr1, 1)

array([120, 230, 150,  60])

In [131]:
arr1

array([120,  85, 230, 150,  60])

In [132]:
#0,2,3
np.delete(arr1, [0,2,3])

array([85, 60])

### Edit element value in array
#### Edit 1 element

In [133]:
arr1 = np.array([120, 85, 230, 150, 60])
arr1

array([120,  85, 230, 150,  60])

In [134]:
arr1[2]

np.int64(230)

In [135]:
# 2
arr1[2] = 80
arr1

array([120,  85,  80, 150,  60])

#### multiple elements

In [136]:
arr1

array([120,  85,  80, 150,  60])

In [137]:
arr1[arr1 < 100]

array([85, 80, 60])

In [138]:
# values less than 100 to 100
arr1[arr1 < 100] = 100
arr1

array([120, 100, 100, 150, 100])

In [140]:
# values equal to 100 to be 1,2,3
arr1[arr1 == 100] = [1,2,3]
arr1


array([120,   1,   2, 150,   3])

In [141]:
arr1[[2,4]]

array([2, 3])

In [142]:
# value at position 2,4
arr1[[2,4]] = [90, 85]
arr1

array([120,   1,  90, 150,  85])

## Arithmetic operations on arrays

In [2]:
arr1 = np.array([120, 85, 230, 150, 60])
arr1

array([120,  85, 230, 150,  60])

In [3]:
arr1 + 10

array([130,  95, 240, 160,  70])

In [4]:
arr1 - 20

array([100,  65, 210, 130,  40])

In [5]:
arr1 * 3

array([360, 255, 690, 450, 180])

In [6]:
arr1 /2

array([ 60. ,  42.5, 115. ,  75. ,  30. ])

In [7]:
arr_a = np.array([110, 50, 60, 80, 100])
arr_b = np.array([90, 65, 75, 85, 105])

In [8]:
arr_a + arr_b

array([200, 115, 135, 165, 205])

## Mathematical functions

In [9]:
arr3 = np.array([1,4,9,16,25])
arr4 = np.array([1,8,27,64,125])

In [10]:
arr3 ** 2

array([  1,  16,  81, 256, 625])

In [11]:

np.square(arr3)

array([  1,  16,  81, 256, 625])

In [12]:

np.sqrt(arr3)

array([1., 2., 3., 4., 5.])

In [13]:
# cube root
np.cbrt(arr4)

array([1., 2., 3., 4., 5.])

In [14]:
arr5 = np.array([4, -2, 6, -9, 3])
# abs
np.abs(arr5)

array([4, 2, 6, 9, 3])

In [15]:
arr6 = np.array([5.423, 8.976, 4.3584, 7.6582])
arr6

array([5.423 , 8.976 , 4.3584, 7.6582])

In [16]:
np.round(arr6, 1)

array([5.4, 9. , 4.4, 7.7])

In [17]:
np.round(arr6)

array([5., 9., 4., 8.])

## Statistical functions

In [18]:
arr1 = np.array([120, 85, 230, 150, 60,200,10])
arr1

array([120,  85, 230, 150,  60, 200,  10])

In [19]:
# Sum
np.sum(arr1)

np.int64(855)

In [20]:
arr1.sum()

np.int64(855)

In [21]:
sum(arr1)

np.int64(855)

In [22]:
# minimum
np.min(arr1)

np.int64(10)

In [23]:
arr1.min()

np.int64(10)

In [24]:
min(arr1)

np.int64(10)

In [25]:
# maximum
np.max(arr1)

np.int64(230)

In [26]:
# average
np.mean(arr1)

np.float64(122.14285714285714)

In [27]:
arr1.mean()

np.float64(122.14285714285714)

In [28]:
arr1

array([120,  85, 230, 150,  60, 200,  10])

In [29]:
# median
#120, 85, 230, 150, 60, 200 10 =>10 60 85 120 150 200 230
np.median(arr1)

np.float64(120.0)

In [31]:
# standard deviation
np.std(arr1)

np.float64(72.0048184328731)

In [32]:
arr1.std()

np.float64(72.0048184328731)

In [33]:
#variance
np.var(arr1)

np.float64(5184.693877551021)

In [34]:
# quartile
print('Q1 =', np.quantile(arr1, 0.25))
print('Q2 =', np.quantile(arr1, 0.5))
print('Q3 =', np.quantile(arr1, 0.75))

Q1 = 72.5
Q2 = 120.0
Q3 = 175.0


## Arrgs

In [35]:
# increasing
np.sort(arr1)

array([ 10,  60,  85, 120, 150, 200, 230])

In [36]:
arr1

array([120,  85, 230, 150,  60, 200,  10])

In [37]:
arr1.sort()

In [38]:
arr1

array([ 10,  60,  85, 120, 150, 200, 230])

In [39]:
# decreasing
np.sort(arr1)[::-1]

array([230, 200, 150, 120,  85,  60,  10])

# Conversion

In [46]:
arr1 = np.array([120, 85, 230, 150, 60,200],dtype=float)
arr1

array([120.,  85., 230., 150.,  60., 200.])

In [47]:
arr1.dtype

dtype('float64')

In [50]:
arr1 = arr1.astype(int)

In [51]:
arr1

array([120,  85, 230, 150,  60, 200])