In [3]:
import numpy as np
import time
import sys

### Data type

In [1]:
my_list = ['Trần Tuấn Anh', 19, 8.5, True]
print(type(my_list), my_list)

<class 'list'> ['Trần Tuấn Anh', 19, 8.5, True]


In [4]:
my_arr = np.array(my_list)
print(type(my_arr), my_arr)

<class 'numpy.ndarray'> ['Trần Tuấn Anh' '19' '8.5' 'True']


In [5]:
np.array([1, 3, False, 5.7, 'hi'])

array(['1', '3', 'False', '5.7', 'hi'], dtype='<U32')

### Storage

In [6]:
# Create a list of integers from 0 to 999999
lst_num = list(range(1000000))

# Memory size
print(f"Memory size of lst_num: {sys.getsizeof(lst_num)}")
print(len(lst_num))


Memory size of lst_num: 8000056
1000000


In [7]:
# Convert the list into a NumPy array with the same data
arr_num = np.array(lst_num, dtype=np.int32)

# Memory size
print(f"Memory size of arr_num: {sys.getsizeof(arr_num)} bytes")
print(arr_num.size)


Memory size of arr_num: 4000112 bytes
1000000


In [10]:
arr_num.dtype

dtype('int64')

### Tasks

In [8]:
# Multiply each element in lst_num by 2
lst_cal = [x * 2 for x in lst_num]
lst_cal[:5]


[0, 2, 4, 6, 8]

In [9]:
# Multiply each element in arr_num by 2
arr_cal = arr_num * 2
arr_cal[:5]


array([0, 2, 4, 6, 8], dtype=int32)

### Speed

In [10]:
# Square each element in lst_num
start_time = time.time()
lst_result = [x ** 2 for x in lst_num]
end_time = time.time()
t0 = end_time - start_time
print(f"Time: {t0:.6f} seconds")
lst_result[:5]


Time: 0.084256 seconds


[0, 1, 4, 9, 16]

In [11]:
# Square each element in arr_num
start_time = time.time()
arr_result = arr_num ** 2
end_time = time.time()
t1 = end_time - start_time
print(f"Time: {t1:.6f} seconds")
arr_result[:5]


Time: 0.008178 seconds


array([ 0,  1,  4,  9, 16], dtype=int32)

## Practice:
Create an array containing the average temperature for each day of the week (degrees C), then convert it to degrees F (degrees F = degrees C * 9/5 + 32)

In [36]:
doc = [30,37,39,41,25]
dof = [(c*9/5 +32) for c in doc]
dof

[86.0, 98.6, 102.2, 105.8, 77.0]

In [37]:
arr_doc = np.array(doc)
arr_dof = arr_doc *9/5 +32
arr_dof

array([ 86. ,  98.6, 102.2, 105.8,  77. ])