In [1]:
import numpy as np

## Array generation

In [2]:
# Create a 2D array representing information about the quantity of different types of products sold each month at a store.
# - Each row represents a type of product.
# - Each column corresponds to a month (from January to May).

arr2 = np.array([[120, 85, 230, 150, 60],
                 [90, 65, 75, 85, 105],
                 [110, 75, 85, 100, 90],
                 [70, 50, 60, 80, 100]])
arr2


array([[120,  85, 230, 150,  60],
       [ 90,  65,  75,  85, 105],
       [110,  75,  85, 100,  90],
       [ 70,  50,  60,  80, 100]])

In [13]:
arr = np.array([[120, 85, 230, 150, 60]])
arr

array([[120,  85, 230, 150,  60]])

In [14]:
arr.shape

(1, 5)

In [3]:
# Create a 3D array representing the quantity of each type of product sold each month at different stores.
# - Each matrix represents a store.
# - Each row represents a type of product.
# - Each column corresponds to a month.
# shape => (3,4,5)

chi_nhanh = np.array([[[120,  85, 230, 150,  60],
                        [ 90,  65,  75,  85, 105],
                        [110,  75,  85, 100,  90],
                        [ 70,  50,  60,  80, 100]],
                       [[192, 219, 181,  64,  54],
                        [134,  60, 125, 186, 174],
                        [ 96,  87, 169, 123, 187],
                        [247, 244, 243, 212, 169]],
                       [[ 65, 153, 186, 214, 141],
                        [113, 124, 223, 176, 161],
                        [163, 240, 138, 242, 112],
                        [179, 119,  60, 214, 206]]])

chi_nhanh


array([[[120,  85, 230, 150,  60],
        [ 90,  65,  75,  85, 105],
        [110,  75,  85, 100,  90],
        [ 70,  50,  60,  80, 100]],

       [[192, 219, 181,  64,  54],
        [134,  60, 125, 186, 174],
        [ 96,  87, 169, 123, 187],
        [247, 244, 243, 212, 169]],

       [[ 65, 153, 186, 214, 141],
        [113, 124, 223, 176, 161],
        [163, 240, 138, 242, 112],
        [179, 119,  60, 214, 206]]])

In [16]:
chi_nhanh.shape

(3, 4, 5)

## Properties

In [18]:
# count elements
arr2.size

20

In [4]:
# A 2D array with 4 rows and 5 columns
arr2.shape

(4, 5)

In [20]:
# 2D array
arr2.ndim

2

In [17]:
# data type of elements in array
arr2.dtype 

dtype('int64')

In [21]:
# item size
arr2.itemsize 

8

## Create arrays from utility functions

In [5]:
# Create a 2D array with 5 rows and 4 columns filled with zeros
arr0 = np.zeros((5,4),dtype=int)
print(arr0)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [6]:
# create a 5 row 4 column array with elements having value 1
arr1 = np.ones((5,4))
print(arr1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
# create a 4 row 3 column array containing elements with value 4
arr_2 = np.full((4,3), fill_value=4)
print(arr_2)

[[4 4 4]
 [4 4 4]
 [4 4 4]
 [4 4 4]]


In [9]:
# generate a random array of 4 rows and 3 columns containing elements from 0 to 1 (excluding 1)np.random.seed(1)
arr3 = np.random.rand(4,3)
print(arr3)

[[0.31916422 0.97351869 0.22003906]
 [0.13394782 0.1731358  0.28687258]
 [0.6167532  0.2280225  0.05650643]
 [0.89112744 0.71789875 0.18272622]]


In [29]:
# generate random array 5 rows 3 columns with elements from 0 to less than 10
np.random.seed(1)
arr4 = np.random.randint(0,10, size=(5,3))
print(arr4)

[[5 8 9]
 [5 0 0]
 [1 7 6]
 [9 2 4]
 [5 2 4]]


In [34]:
#### Create array from shark.tsv file
shark = np.genfromtxt('shark.tsv',delimiter='\t',skip_header=1,filling_values=-1,dtype=int)
shark

array([[ -1,  28,  94,  68],
       [ -1,  27,  78,  32],
       [ -1,  66,  63,  34],
       [ -1, 103,  54,  25],
       [ -1, 106,  21,  25],
       [ -1, 173,  25,  22],
       [ -1, 232,  25,  28],
       [ -1, 208,  28,  15],
       [ -1, 182,  35,  17],
       [ -1, 141,  56,  16],
       [ -1,  79,  65,  20],
       [ -1,  37,  94,  46]])


# Ex. Create array from baseball_2D.txt file

In [36]:
baseball = np.genfromtxt('baseball_2D.txt',  delimiter= ',')
baseball[:30]

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan])

In [37]:
with open('baseball_2D.txt') as f:
    dt = f.read()
dt

'[[74, 180], [74, 215], [72, 210], [72, 210], [73, 188], [69, 176], [69, 209], [71, 200], [76, 231], [71, 180], [73, 188], [73, 180], [74, 185], [74, 160], [69, 180], [70, 185], [73, 189], [75, 185], [78, 219], [79, 230], [76, 205], [74, 230], [76, 195], [72, 180], [71, 192], [75, 225], [77, 203], [74, 195], [73, 182], [74, 188], [78, 200], [73, 180], [75, 200], [73, 200], [75, 245], [75, 240], [74, 215], [69, 185], [71, 175], [74, 199], [73, 200], [73, 215], [76, 200], [74, 205], [74, 206], [70, 186], [72, 188], [77, 220], [74, 210], [70, 195], [73, 200], [75, 200], [76, 212], [76, 224], [78, 210], [74, 205], [74, 220], [76, 195], [77, 200], [81, 260], [78, 228], [75, 270], [77, 200], [75, 210], [76, 190], [74, 220], [72, 180], [72, 205], [75, 210], [73, 220], [73, 211], [73, 200], [70, 180], [70, 190], [70, 170], [76, 230], [68, 155], [71, 185], [72, 185], [75, 200], [75, 225], [75, 225], [75, 220], [68, 160], [74, 205], [78, 235], [71, 250], [73, 210], [76, 190], [74, 160], [74, 200

In [38]:
dt = eval(dt)
dt

[[74, 180],
 [74, 215],
 [72, 210],
 [72, 210],
 [73, 188],
 [69, 176],
 [69, 209],
 [71, 200],
 [76, 231],
 [71, 180],
 [73, 188],
 [73, 180],
 [74, 185],
 [74, 160],
 [69, 180],
 [70, 185],
 [73, 189],
 [75, 185],
 [78, 219],
 [79, 230],
 [76, 205],
 [74, 230],
 [76, 195],
 [72, 180],
 [71, 192],
 [75, 225],
 [77, 203],
 [74, 195],
 [73, 182],
 [74, 188],
 [78, 200],
 [73, 180],
 [75, 200],
 [73, 200],
 [75, 245],
 [75, 240],
 [74, 215],
 [69, 185],
 [71, 175],
 [74, 199],
 [73, 200],
 [73, 215],
 [76, 200],
 [74, 205],
 [74, 206],
 [70, 186],
 [72, 188],
 [77, 220],
 [74, 210],
 [70, 195],
 [73, 200],
 [75, 200],
 [76, 212],
 [76, 224],
 [78, 210],
 [74, 205],
 [74, 220],
 [76, 195],
 [77, 200],
 [81, 260],
 [78, 228],
 [75, 270],
 [77, 200],
 [75, 210],
 [76, 190],
 [74, 220],
 [72, 180],
 [72, 205],
 [75, 210],
 [73, 220],
 [73, 211],
 [73, 200],
 [70, 180],
 [70, 190],
 [70, 170],
 [76, 230],
 [68, 155],
 [71, 185],
 [72, 185],
 [75, 200],
 [75, 225],
 [75, 225],
 [75, 220],
 [68

In [39]:
arr_dt = np.array(dt)
arr_dt[:30]

array([[ 74, 180],
       [ 74, 215],
       [ 72, 210],
       [ 72, 210],
       [ 73, 188],
       [ 69, 176],
       [ 69, 209],
       [ 71, 200],
       [ 76, 231],
       [ 71, 180],
       [ 73, 188],
       [ 73, 180],
       [ 74, 185],
       [ 74, 160],
       [ 69, 180],
       [ 70, 185],
       [ 73, 189],
       [ 75, 185],
       [ 78, 219],
       [ 79, 230],
       [ 76, 205],
       [ 74, 230],
       [ 76, 195],
       [ 72, 180],
       [ 71, 192],
       [ 75, 225],
       [ 77, 203],
       [ 74, 195],
       [ 73, 182],
       [ 74, 188]])

## Retrieve
### Retrieve 1 element

In [ ]:
# tenmang[index dong , index cot]

In [40]:
arr2

array([[120,  85, 230, 150,  60],
       [ 90,  65,  75,  85, 105],
       [110,  75,  85, 100,  90],
       [ 70,  50,  60,  80, 100]])

In [41]:
arr2[0,0] # Element value at row index = 0, column index = 0

np.int64(120)

In [42]:
arr2[0,2] # Element value at row index = 0, column index = 2

np.int64(230)

In [43]:
arr2[-1,-1]

np.int64(100)

In [44]:
arr2[0,-1]

np.int64(60)

In [45]:
chi_nhanh

array([[[120,  85, 230, 150,  60],
        [ 90,  65,  75,  85, 105],
        [110,  75,  85, 100,  90],
        [ 70,  50,  60,  80, 100]],

       [[192, 219, 181,  64,  54],
        [134,  60, 125, 186, 174],
        [ 96,  87, 169, 123, 187],
        [247, 244, 243, 212, 169]],

       [[ 65, 153, 186, 214, 141],
        [113, 124, 223, 176, 161],
        [163, 240, 138, 242, 112],
        [179, 119,  60, 214, 206]]])

In [46]:
chi_nhanh.shape

(3, 4, 5)

In [51]:
chi_nhanh[1,0,1]

np.int64(219)

### Retrieve multiple elements by index list

In [89]:
arr2

array([[120,  85, 230, 150,  60],
       [ 90,  65,  75,  85, 105],
       [110,  75,  85, 100,  90],
       [ 70,  50,  60,  80, 100]])

In [ ]:
#irregular row, regular column
# name[ list(list,arr) row index , start : stop : step]

In [10]:
# 120 230 60 => row 0 column 0,2,4
# 90 75 105 => row 1 column 0,2,4
# 70 60 100 => row 3 column 0,2,4
arr2[[0,1,3],::2]

array([[120, 230,  60],
       [ 90,  75, 105],
       [ 70,  60, 100]])

In [ ]:
#rows follow rules, columns do not follow rules
# name[start : stop : step , column index list]

In [92]:
# 120 85 60 => row 0 column 0,1,4
# 90 65 105 => row 1 column 0,1,4
arr2[:2,[0,1,4]]

array([[120,  85,  60],
       [ 90,  65, 105]])

In [ ]:
#irregular row, irregular column
# domainname[row index list, column index list]

In [93]:
arr2

array([[120,  85, 230, 150,  60],
       [ 90,  65,  75,  85, 105],
       [110,  75,  85, 100,  90],
       [ 70,  50,  60,  80, 100]])

In [94]:
# 120 => row 0 column 0
# 65 => row 1 column 1
# 100 => row -1 column -1
arr2[[0,1,-1],[0,1,-1]]

array([120,  65, 100])

In [95]:
#85, 150 => row 0,0 column 1,3
#75 => row 1 column 2
#100 90 => row 2,2 column -2,-1
arr2[[0,0,1,2,2],[1,3,2,-2,-1]]

array([ 85, 150,  75, 100,  90])

### Retrieve multiple elements by slice

In [ ]:
# tenmang[start:stop:step ,start:stop:step ]

In [ ]:
# dimension of output array
# - equal to original array => access by stop:start:step
# - less than original array by 1 => access by fixed index

In [52]:
arr2

array([[120,  85, 230, 150,  60],
       [ 90,  65,  75,  85, 105],
       [110,  75,  85, 100,  90],
       [ 70,  50,  60,  80, 100]])

In [53]:
# Display row 2 value
a = arr2[2,:] 
a

array([110,  75,  85, 100,  90])

In [85]:
b = arr2[2:3]
b

array([[110,  75,  85, 100,  90]])

In [88]:
print(a[0])
print(b[0,0])

110
110


In [58]:
# Display col 1 value
arr2[:,1]

array([85, 65, 75, 50])

In [56]:
arr2

array([[120,  85, 230, 150,  60],
       [ 90,  65,  75,  85, 105],
       [110,  75,  85, 100,  90],
       [ 70,  50,  60,  80, 100]])

In [59]:
# Display 2 first rows value
arr2[0:2:1,:] 

array([[120,  85, 230, 150,  60],
       [ 90,  65,  75,  85, 105]])

In [60]:
arr2[:2]

array([[120,  85, 230, 150,  60],
       [ 90,  65,  75,  85, 105]])

In [12]:
# Display the values of the last 2 rows
arr2[-2:]

array([[110,  75,  85, 100,  90],
       [ 70,  50,  60,  80, 100]])

In [11]:
# Display the values of the first 2 columns
arr2[:,:2]

array([[120,  85],
       [ 90,  65],
       [110,  75],
       [ 70,  50]])

In [13]:
# # Display the values of the last 2 columns
arr2[:,-2:]

array([[150,  60],
       [ 85, 105],
       [100,  90],
       [ 80, 100]])

In [64]:
arr2

array([[120,  85, 230, 150,  60],
       [ 90,  65,  75,  85, 105],
       [110,  75,  85, 100,  90],
       [ 70,  50,  60,  80, 100]])

In [14]:
# Display values of first 2 rows and first 2 columns
arr2[:2,:2]

array([[120,  85],
       [ 90,  65]])

In [15]:
#Combine the display of elements in the array
arr2[::2,1:3]

array([[ 85, 230],
       [ 75,  85]])

In [69]:
arr2

array([[120,  85, 230, 150,  60],
       [ 90,  65,  75,  85, 105],
       [110,  75,  85, 100,  90],
       [ 70,  50,  60,  80, 100]])

In [17]:
# 65 75 => row 1 column 1,2
# 75 85 => row 2 column 1,2
arr2[1:3,1:3]

array([[65, 75],
       [75, 85]])

In [16]:
# 85 100 90 => row 2 column 2,3,4
# 60 80 100 => row 3 column 2,3,4
arr2[2:,2:]

array([[ 85, 100,  90],
       [ 60,  80, 100]])

In [76]:
arr2[-2:,-3:]

array([[ 85, 100,  90],
       [ 60,  80, 100]])

In [77]:
arr2

array([[120,  85, 230, 150,  60],
       [ 90,  65,  75,  85, 105],
       [110,  75,  85, 100,  90],
       [ 70,  50,  60,  80, 100]])

In [18]:
# 85 60 => row 0 column 1.4
# 75 90 => row 2 column 1.4
arr2[::2,1::3]

array([[85, 60],
       [75, 90]])

In [19]:
#120, 230, 60 => row 0 column 0,2,4
# 70, 60, 100 => row 3 column 0,2,4
arr2[::3,::2]

array([[120, 230,  60],
       [ 70,  60, 100]])

### Retrieve element by condition

In [96]:
arr2

array([[120,  85, 230, 150,  60],
       [ 90,  65,  75,  85, 105],
       [110,  75,  85, 100,  90],
       [ 70,  50,  60,  80, 100]])

In [97]:
arr2 < 70

array([[False, False, False, False,  True],
       [False,  True, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True, False, False]])

In [98]:
# Display elements with values <70
arr2[arr2 < 70]

array([60, 65, 50, 60])

In [99]:
arr2[:, 3] >= 100

array([ True, False,  True, False])

In [20]:
# Display the value of the data row with column value 3 >100
arr2[arr2[:, 3] >= 100]

array([[120,  85, 230, 150,  60],
       [110,  75,  85, 100,  90]])

In [101]:
arr2[2] >= 100

array([ True, False, False,  True, False])

In [21]:
# Display the data column value with row 2 value >100
arr2[:,arr2[2] >= 100]

array([[120, 150],
       [ 90,  85],
       [110, 100],
       [ 70,  80]])

### Retrieve elements based on multiple conditions

In [22]:
# Display elements with values from 100 to 200
arr2[(arr2 > 100) & (arr2 < 200)] # and

array([120, 150, 105, 110])

In [23]:
# Display elements with value <= 50 or >= 150
arr2[(arr2 <= 50) | (arr2 >= 150)] # or

array([230, 150,  50])

In [24]:
# Display elements with values no less than 100
arr2[~(arr2 < 100)] # not

array([120, 230, 150, 105, 110, 100, 100])

In [25]:
# Display rows with column 0 value >= 90 and column 3 value >=100
arr2[(arr2[:, 0] >= 90) & (arr2[:, 3] >= 100)]

array([[120,  85, 230, 150,  60],
       [110,  75,  85, 100,  90]])

### Access elements based on conditions with np.where

In [109]:
arr2

array([[120,  85, 230, 150,  60],
       [ 90,  65,  75,  85, 105],
       [110,  75,  85, 100,  90],
       [ 70,  50,  60,  80, 100]])

In [26]:
# Index of elements with values less than 70
idx = np.where(arr2 < 70)
idx


(array([0, 1, 3, 3]), array([4, 1, 1, 2]))

In [27]:
# Display elements with values less than 70
arr2[idx]

array([60, 65, 50, 60])

## Add, delete, edit array data
### Add element to the end of array

In [112]:
arr2

array([[120,  85, 230, 150,  60],
       [ 90,  65,  75,  85, 105],
       [110,  75,  85, 100,  90],
       [ 70,  50,  60,  80, 100]])

In [28]:
# Add 1 line to arr2
row_append = [[75, 80, 95, 110, 160]]
arr3 = np.concatenate([arr2, row_append], axis=0)
arr3

array([[120,  85, 230, 150,  60],
       [ 90,  65,  75,  85, 105],
       [110,  75,  85, 100,  90],
       [ 70,  50,  60,  80, 100],
       [ 75,  80,  95, 110, 160]])

In [115]:
# Add lines to arr2
rows_append = np.array([[ 50,  60,  70,  80, 120], [60,  70,  80,  90, 130]])
rows_append

array([[ 50,  60,  70,  80, 120],
       [ 60,  70,  80,  90, 130]])

In [116]:
arr3 = np.concatenate([arr2, rows_append], axis=0)
arr3

array([[120,  85, 230, 150,  60],
       [ 90,  65,  75,  85, 105],
       [110,  75,  85, 100,  90],
       [ 70,  50,  60,  80, 100],
       [ 50,  60,  70,  80, 120],
       [ 60,  70,  80,  90, 130]])

In [117]:
# Add 1 col to arr2
new_col = np.array([[110,  90, 120,  80 ]])
new_col

array([[110,  90, 120,  80]])

In [120]:
new_col.shape

(1, 4)

In [121]:
new_col.T

array([[110],
       [ 90],
       [120],
       [ 80]])

In [119]:
arr2.shape

(4, 5)

In [122]:
arr3 = np.concatenate([arr2, new_col.T], axis=1)
arr3

array([[120,  85, 230, 150,  60, 110],
       [ 90,  65,  75,  85, 105,  90],
       [110,  75,  85, 100,  90, 120],
       [ 70,  50,  60,  80, 100,  80]])

In [123]:
# Add cols to arr2
new_cols = np.array([[120, 130, 140],
                     [110, 120, 130],
                     [130, 140, 150],
                     [ 95, 100, 110]])
new_cols

array([[120, 130, 140],
       [110, 120, 130],
       [130, 140, 150],
       [ 95, 100, 110]])

In [124]:
new_cols.shape

(4, 3)

In [125]:
arr3= np.concatenate([arr2, new_cols], axis=1)
arr3

array([[120,  85, 230, 150,  60, 120, 130, 140],
       [ 90,  65,  75,  85, 105, 110, 120, 130],
       [110,  75,  85, 100,  90, 130, 140, 150],
       [ 70,  50,  60,  80, 100,  95, 100, 110]])

### Insert an element into the array at the specified position, using np.insert()

In [126]:
arr2

array([[120,  85, 230, 150,  60],
       [ 90,  65,  75,  85, 105],
       [110,  75,  85, 100,  90],
       [ 70,  50,  60,  80, 100]])

In [29]:
# Insert a line into arr2
new_row = np.array([ 180,  57,  58,  68, 90])
arr5 = np.insert(arr2, 3, new_row, axis=0)
arr5

array([[120,  85, 230, 150,  60],
       [ 90,  65,  75,  85, 105],
       [110,  75,  85, 100,  90],
       [180,  57,  58,  68,  90],
       [ 70,  50,  60,  80, 100]])

In [30]:
# Insert a col into arr2
new_col = np.array([ 80,  75,  85,  60])
arr5 = np.insert(arr2, 4, new_col.T, axis=1)
arr5

array([[120,  85, 230, 150,  80,  60],
       [ 90,  65,  75,  85,  75, 105],
       [110,  75,  85, 100,  85,  90],
       [ 70,  50,  60,  80,  60, 100]])

In [129]:
arr2

array([[120,  85, 230, 150,  60],
       [ 90,  65,  75,  85, 105],
       [110,  75,  85, 100,  90],
       [ 70,  50,  60,  80, 100]])

In [31]:
# Insert cols into arr2
new_cols = np.array([[ 70,  95],
                   [ 60,  80],
                   [ 70, 100],
                   [ 55,  70]])
new_cols

array([[ 70,  95],
       [ 60,  80],
       [ 70, 100],
       [ 55,  70]])

In [131]:
arr5 = np.insert(arr2, [3,4],new_cols, axis=1)
arr5

array([[120,  85, 230,  70, 150,  95,  60],
       [ 90,  65,  75,  60,  85,  80, 105],
       [110,  75,  85,  70, 100, 100,  90],
       [ 70,  50,  60,  55,  80,  70, 100]])

### Delete Element
Before deleting a column, you should consider carefully and ensure that the deletion does not lose important information and does not affect your goals in analyzing or processing the data.

In [132]:
arr2

array([[120,  85, 230, 150,  60],
       [ 90,  65,  75,  85, 105],
       [110,  75,  85, 100,  90],
       [ 70,  50,  60,  80, 100]])

In [32]:
# Delete columns 1 and 3 in arr2
np.delete(arr2, [1,3], axis=1)

array([[120, 230,  60],
       [ 90,  75, 105],
       [110,  85,  90],
       [ 70,  60, 100]])

In [134]:
arr2

array([[120,  85, 230, 150,  60],
       [ 90,  65,  75,  85, 105],
       [110,  75,  85, 100,  90],
       [ 70,  50,  60,  80, 100]])

In [33]:
# Delete rows 0 and 3 in arr2
np.delete(arr2, [0,3], axis=0)

array([[ 90,  65,  75,  85, 105],
       [110,  75,  85, 100,  90]])

### Edit element value in array
#### Edit 1 element

In [136]:
arr2

array([[120,  85, 230, 150,  60],
       [ 90,  65,  75,  85, 105],
       [110,  75,  85, 100,  90],
       [ 70,  50,  60,  80, 100]])

In [34]:
# Change the value at row 2, column 4 to 100
arr2[2,4] = 100
arr2

array([[120,  85, 230, 150,  60],
       [ 90,  65,  75,  85, 105],
       [110,  75,  85, 100, 100],
       [ 70,  50,  60,  80, 100]])

#### Edit multiple elements

In [138]:
arr2

array([[120,  85, 230, 150,  60],
       [ 90,  65,  75,  85, 105],
       [110,  75,  85, 100, 100],
       [ 70,  50,  60,  80, 100]])

In [139]:
arr2[:, 1] + 10

array([95, 75, 85, 60])

In [35]:
# Increment the value of column 1 by 10
arr2[:, 1] = arr2[:, 1] + 10
arr2

array([[120,  95, 230, 150,  60],
       [ 90,  75,  75,  85, 105],
       [110,  85,  85, 100, 100],
       [ 70,  60,  60,  80, 100]])

In [141]:
arr2[[0,2], 1:3]

array([[ 95, 230],
       [ 85,  85]])

In [ ]:
 [[ 90, 200],
  [ 65,  95]]

In [36]:
# Modify value
arr2[[0,2], 1:3] = [[ 90, 200],[ 65, 95]]
arr2

array([[120,  90, 200, 150,  60],
       [ 90,  75,  75,  85, 105],
       [110,  65,  95, 100, 100],
       [ 70,  60,  60,  80, 100]])

In [143]:
arr2[(arr2>=80)&(arr2<=90)] 

array([90, 90, 85, 80])

In [38]:
# Fix values from 80 to 90 to be 100
arr2[(arr2>=80)&(arr2<=90)] = 100
arr2

array([[120, 100, 200, 150,  60],
       [100,  75,  75, 100, 105],
       [110,  65,  95, 100, 100],
       [ 70,  60,  60, 100, 100]])

## Arithmetic operations

In [39]:
# Create a 1-dimensional array arr1
arr1= np.array([120, 85, 230, 150, 60])
arr1

array([120,  85, 230, 150,  60])

In [40]:
# Create 2D array arr2
arr2 = np.array([[120, 85, 230, 150, 60],
[90, 65, 75, 85, 105],
[110, 75, 85, 100, 90],
[70, 50, 60, 80, 100]])
arr2

array([[120,  85, 230, 150,  60],
       [ 90,  65,  75,  85, 105],
       [110,  75,  85, 100,  90],
       [ 70,  50,  60,  80, 100]])

In [148]:
# Broadcasting
arr2 - 50

array([[ 70,  35, 180, 100,  10],
       [ 40,  15,  25,  35,  55],
       [ 60,  25,  35,  50,  40],
       [ 20,   0,  10,  30,  50]])

In [41]:

arr1 + arr2

array([[240, 170, 460, 300, 120],
       [210, 150, 305, 235, 165],
       [230, 160, 315, 250, 150],
       [190, 135, 290, 230, 160]])

In [42]:

arr1 - arr2

array([[  0,   0,   0,   0,   0],
       [ 30,  20, 155,  65, -45],
       [ 10,  10, 145,  50, -30],
       [ 50,  35, 170,  70, -40]])

In [43]:

arr1 * arr2

array([[14400,  7225, 52900, 22500,  3600],
       [10800,  5525, 17250, 12750,  6300],
       [13200,  6375, 19550, 15000,  5400],
       [ 8400,  4250, 13800, 12000,  6000]])

In [44]:

arr1 / arr2

array([[1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.33333333, 1.30769231, 3.06666667, 1.76470588, 0.57142857],
       [1.09090909, 1.13333333, 2.70588235, 1.5       , 0.66666667],
       [1.71428571, 1.7       , 3.83333333, 1.875     , 0.6       ]])

## Using Mathematical Functions in Numpy

In [49]:
arr3 = np.array([[1,4,9,16,25],
                [36,49,64,81,100]])
arr4 = np.array([[1,8,27,64,125],
                [216,343,512,729,1000]])

In [50]:
arr3 + arr4

array([[   2,   12,   36,   80,  150],
       [ 252,  392,  576,  810, 1100]])

In [51]:
# Square
np.square(arr3)

array([[    1,    16,    81,   256,   625],
       [ 1296,  2401,  4096,  6561, 10000]])

In [52]:
# Square root
np.sqrt(arr3)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [53]:
# cube root
np.cbrt(arr4)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [54]:
arr5 = np.array([[4, -2, 6, -9, 3],
                 [-5, 8, 7, -10, 1]])
np.abs(arr5)

array([[ 4,  2,  6,  9,  3],
       [ 5,  8,  7, 10,  1]])

In [55]:
arr6 = np.array([[5.423, 8.976, 4.3584, 7.6582],
                 [10.954, 9.219, 15.165, 12.247]])
arr6

array([[ 5.423 ,  8.976 ,  4.3584,  7.6582],
       [10.954 ,  9.219 , 15.165 , 12.247 ]])

In [56]:
np.round(arr6, 1)

array([[ 5.4,  9. ,  4.4,  7.7],
       [11. ,  9.2, 15.2, 12.2]])

## Statistics on array

In [57]:
# Create a 2D array arr2
arr2 = np.array([[120, 85, 230, 150, 60],
                 [90, 65, 75, 85, 105],
                 [110, 75, 85, 100, 90],
                 [70, 50, 60, 80, 100]])

arr2


array([[120,  85, 230, 150,  60],
       [ 90,  65,  75,  85, 105],
       [110,  75,  85, 100,  90],
       [ 70,  50,  60,  80, 100]])

In [ ]:
# Statistics on the entire array

In [58]:
# Sum all elements in array
np.sum(arr2)

1885

In [59]:
# smallest element in array
np.min(arr2)

50

In [60]:
# largest element in array
np.max(arr2)

230

In [61]:
# mean of array
np.mean(arr2)

94.25

In [62]:
# median of array
np.median(arr2)

85.0

In [63]:
# array standard deviation
np.std(arr2)

38.47970244167696

In [64]:
# variance of array
np.var(arr2)

1480.6875

In [65]:
# quartiles of array
print('Q1 =', np.quantile(arr2, 0.25))
print('Q2 =', np.quantile(arr2, 0.5))
print('Q3 =', np.quantile(arr2, 0.75))

Q1 = 73.75
Q2 = 85.0
Q3 = 101.25


In [ ]:
# Count rows in column (axis = 0)

In [66]:
arr2

array([[120,  85, 230, 150,  60],
       [ 90,  65,  75,  85, 105],
       [110,  75,  85, 100,  90],
       [ 70,  50,  60,  80, 100]])

In [67]:
print('Sum of rows in column', np.sum(arr2, axis = 0))

print('Min of rows in column', np.min(arr2, axis = 0))

print('Max of rows in column', np.max(arr2, axis = 0))

print('Mean of rows in column', np.mean(arr2, axis = 0))

Sum of rows in column [390 275 450 415 355]
Min of rows in column [70 50 60 80 60]
Max of rows in column [120  85 230 150 105]
Mean of rows in column [ 97.5   68.75 112.5  103.75  88.75]


In [ ]:
# Count columns in row

In [68]:
print('Sum of columns in row', np.sum(arr2, axis = 1))

print('Min of columns in row', np.min(arr2, axis = 1))

print('Max of columns in row', np.max(arr2, axis = 1))

print('Mean of columns in row', np.mean(arr2, axis = 1))

Sum of columns in row [645 420 460 360]
Min of columns in row [60 65 75 50]
Max of columns in row [230 105 110 100]
Mean of columns in row [129.  84.  92.  72.]


### Correlation Coefficient

In [ ]:
arr_a = np.array([ 90,  65,  75,  85, 105])
arr_b = np.array([110,  75,  85, 100,  90])

In [ ]:
arr_a

In [ ]:
arr_b

In [ ]:
np.corrcoef(arr_a, arr_b)

## Sort array

In [69]:
arr2

array([[120,  85, 230, 150,  60],
       [ 90,  65,  75,  85, 105],
       [110,  75,  85, 100,  90],
       [ 70,  50,  60,  80, 100]])

In [70]:
np.sort(arr2)

array([[ 60,  85, 120, 150, 230],
       [ 65,  75,  85,  90, 105],
       [ 75,  85,  90, 100, 110],
       [ 50,  60,  70,  80, 100]])

In [71]:
np.sort(arr2, axis = 1) # sort by row

array([[ 60,  85, 120, 150, 230],
       [ 65,  75,  85,  90, 105],
       [ 75,  85,  90, 100, 110],
       [ 50,  60,  70,  80, 100]])

In [72]:
np.sort(arr2, axis = 0) # sort by column

array([[ 70,  50,  60,  80,  60],
       [ 90,  65,  75,  85,  90],
       [110,  75,  85, 100, 100],
       [120,  85, 230, 150, 105]])

In [73]:
arr2

array([[120,  85, 230, 150,  60],
       [ 90,  65,  75,  85, 105],
       [110,  75,  85, 100,  90],
       [ 70,  50,  60,  80, 100]])

In [74]:
sorted_indices = np.argsort(arr2[:, 0])
sorted_indices

array([3, 1, 2, 0])

In [75]:
# Sort array ascending by column 0
sorted_indices = np.argsort(arr2[:, 0])
sorted_arr = arr2[sorted_indices, :]
sorted_arr

array([[ 70,  50,  60,  80, 100],
       [ 90,  65,  75,  85, 105],
       [110,  75,  85, 100,  90],
       [120,  85, 230, 150,  60]])

In [76]:
arr2

array([[120,  85, 230, 150,  60],
       [ 90,  65,  75,  85, 105],
       [110,  75,  85, 100,  90],
       [ 70,  50,  60,  80, 100]])

In [77]:
sorted_indices = np.argsort(arr2[1, :])
sorted_indices

array([1, 2, 3, 0, 4])

In [78]:
# Sort array ascending by row 1
sorted_indices = np.argsort(arr2[1, :])
sorted_arr = arr2[:, sorted_indices]
sorted_arr

array([[ 85, 230, 150, 120,  60],
       [ 65,  75,  85,  90, 105],
       [ 75,  85, 100, 110,  90],
       [ 50,  60,  80,  70, 100]])

## Transform array
### Reshape

In [79]:
# Create a 1-dimensional array arr1
arr1= np.array([120, 85, 230, 150, 60, 90])
arr1

array([120,  85, 230, 150,  60,  90])

In [80]:
# Convert 1D array to 2D array (2 rows 3 columns)
arr1.reshape(2,3)

array([[120,  85, 230],
       [150,  60,  90]])

In [81]:
arr1.reshape(6,1)

array([[120],
       [ 85],
       [230],
       [150],
       [ 60],
       [ 90]])

In [82]:
arr2

array([[120,  85, 230, 150,  60],
       [ 90,  65,  75,  85, 105],
       [110,  75,  85, 100,  90],
       [ 70,  50,  60,  80, 100]])

In [83]:
# Convert 2D array to 1D array
arr2.reshape(20)

array([120,  85, 230, 150,  60,  90,  65,  75,  85, 105, 110,  75,  85,
       100,  90,  70,  50,  60,  80, 100])

In [84]:
# Note:
arr2.reshape(1,20) # 2-dimensional array

array([[120,  85, 230, 150,  60,  90,  65,  75,  85, 105, 110,  75,  85,
        100,  90,  70,  50,  60,  80, 100]])

In [85]:
arr2.reshape(1,-1)

array([[120,  85, 230, 150,  60,  90,  65,  75,  85, 105, 110,  75,  85,
        100,  90,  70,  50,  60,  80, 100]])

In [86]:
arr2.reshape(-1)

array([120,  85, 230, 150,  60,  90,  65,  75,  85, 105, 110,  75,  85,
       100,  90,  70,  50,  60,  80, 100])

In [87]:
arr2.ravel()

array([120,  85, 230, 150,  60,  90,  65,  75,  85, 105, 110,  75,  85,
       100,  90,  70,  50,  60,  80, 100])

In [88]:
arr2.flatten()

array([120,  85, 230, 150,  60,  90,  65,  75,  85, 105, 110,  75,  85,
       100,  90,  70,  50,  60,  80, 100])

In [89]:
# Convert array arr2 to 2D array: 5 rows, 4 columns
arr2.reshape(5,4)

array([[120,  85, 230, 150],
       [ 60,  90,  65,  75],
       [ 85, 105, 110,  75],
       [ 85, 100,  90,  70],
       [ 50,  60,  80, 100]])

In [90]:
arr2

array([[120,  85, 230, 150,  60],
       [ 90,  65,  75,  85, 105],
       [110,  75,  85, 100,  90],
       [ 70,  50,  60,  80, 100]])

In [91]:
arr2.transpose()

array([[120,  90, 110,  70],
       [ 85,  65,  75,  50],
       [230,  75,  85,  60],
       [150,  85, 100,  80],
       [ 60, 105,  90, 100]])

In [92]:
arr2.T

array([[120,  90, 110,  70],
       [ 85,  65,  75,  50],
       [230,  75,  85,  60],
       [150,  85, 100,  80],
       [ 60, 105,  90, 100]])

## Combine data

In [93]:
arr1

array([120,  85, 230, 150,  60,  90])

In [94]:
arr3 = np.array([95, 80, 120, 60, 150])

In [95]:
# Element appears in both arrays arr1, arr3
np.intersect1d(arr1, arr3)

array([ 60, 120, 150])

In [96]:
# Element appears only in arr1 but not in arr3
np.setdiff1d(arr1, arr3)

array([ 85,  90, 230])

In [97]:
# Element appears only in arr3 but not in arr1
np.setdiff1d(arr3, arr1)

array([80, 95])